### PR TITLE
add task and host info to the events list

### PR DESCRIPTION
**Pull request by Daniel-Pivonka**

### CODE REVIEW

**Comment by Daniel-Pivonka** [comment]
I improved the var names,
made the output a list of dicts,
and fixed the opening of the file twice.

Im working on figuring out how to get the status its not as simple as the other 2 fields,

and do you have any recommendations how to parallelize this?

**Comment by Daniel-Pivonka** [comment]
also this line https://github.com/pcuzner/ansible-runner-service/blob/768ab13cca1b94cad8d7c1d594b524950baa92fa/runner_service/services/jobs.py#L34 caused me errors. i commented it out for the time being as it doesnt seem to be doing anything

**Comment by pcuzner** [comment]
I'd look at the Queue module and introduce a producer/consumer model for reading the events to extract the information you need in parallel

**Comment by pcuzner** [comment]
As far as status goes, don't the tasks have an rc field? 0=successful? Maybe a question for ansible_runner forum?

**Comment by Daniel-Pivonka** [comment]
ive parallelized my process. limiting the number of threads to 10 for now. and ive added a status although i dont think the status is perfect but i want to know what you think?

**Pull request closed without merging**
